/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://nuv5zj2525ctjjqjx3a5w3yrsi.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-synitai6fzhpdn55myookrutpi",
  aws_cognito_identity_pool_id:
    "us-east-1:1ebee28f-ba0f-4265-88e1-7feb5ad46476",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_j0n2jPyQJ",
  aws_user_pools_web_client_id: "dpautbet9btdef4p12aq64s0c",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL", "NAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
